config/routes.rb
Rails.application.routes.draw do
  get 'trips/show'
  get 'trips/arrived'

  get 'buses/show'
  get 'itineraries/index'
  get 'itineraries/show'
  post 'itineraries/favorites'
  get 'itineraries/favorites'
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :itineraries, only: %i[index show] do
    member do
      patch :mark_as_favorite
    end

    collection do
      get :favorites
    end
  end

  resources :buses, only: %i[show update]

  resources :trips, only: %i[create show] do
    member do
      patch :completed
    end
  end
end

app/models/itinerary.rb
class Itinerary < ApplicationRecord
  belongs_to :user
  has_many :itinerary_buses, dependent: :destroy
  has_many :buses, through: :itinerary_buses

  geocoded_by :starting_point
  geocoded_by :end_point
  after_validation :geocode, if: :will_save_change_to_starting_point?
  after_validation :geocode, if: :will_save_change_to_end_point?
end

app/controllers/itineraries_controller.rb
class ItinerariesController < ApplicationController
  def index
    if params[:departure].present? && params[:arrival].present?
      @itinerary = Itinerary.new(starting_point: params[:departure], end_point: params[:arrival])
      @itinerary.user = current_user

      @departing = Geocoder.coordinates(@itinerary.starting_point).join(",")+",200"
      @arrival = Geocoder.coordinates(@itinerary.end_point).join(",")+",200"

      @itineraries_data = FetchItineraryService.new(@departing, @arrival).call

      @itineraries = @itineraries_data.map do |iti|

        bus = Bus.find_or_create_by!(
          star_bus_id: iti[:bus_id]
        )

        bus.star_line_short_name = iti[:bus_name]
        bus.star_line_id = iti[:star_line_id]
        bus.star_destination = iti[:star_destination]

        bus.save

        itinerary = Itinerary.create!(
          user: current_user,
          starting_point: iti[:starting_point],
          end_point: iti[:end_point],
          departing_time: iti[:departing_time],
          arrival_time: iti[:arrival_time],
          route: iti[:coordinates],
          colour: Line.find_by(star_line_id: bus.star_line_id)&.colour || "#47B1FF"
        )

        ItineraryBus.create!(
          bus: bus,
          itinerary: itinerary,
          starting_point: itinerary.starting_point,
          end_point: itinerary.end_point,
          departing_time: iti[:departing_time],
          arrival_time: iti[:arrival_time]
        )
        itinerary
        # @itinerary = Itinerary.find(params[:id])
        # @iti_bus = @itinerary.itinerary_buses.first
        # @bus = @iti_bus.bus
        # @direction = @bus.star_destination
        # @star_short_name = @bus.star_line_short_name

      end
      @dep_coordinates = Geocoder.coordinates(params[:departure])
      @ari_coordinates = Geocoder.coordinates(params[:arrival])


      @markers = [
        {
          lat: @dep_coordinates.first,
          lng: @dep_coordinates.last,
          image_url: helpers.asset_url('starting_point.svg')
        },
        {
          lat: @ari_coordinates.first,
          lng: @ari_coordinates.last,
          image_url: helpers.asset_url('end_point.svg')
        }
      ]

      # @route = @itineraries_data.first[:coordinates] if @itineraries_data.length > 1
    end
  end

  def show
    @itinerary = Itinerary.find(params[:id])

    @starting_point = @itinerary.route.split(";").first.split(",").map(&:to_f)
    @end_point = @itinerary.route.split(";").last.split(",").map(&:to_f)

    # @starting_point = BusStop.find_by(name: @itinerary.starting_point)
    # @end_point = BusStop.find_by(name: @itinerary.end_point)

    if @starting_point && @end_point
      @markers = [
        {
          lng: @starting_point.first,
          lat: @starting_point.last,
          image_url: helpers.asset_url('starting_point.svg')
        },
        {
          lng: @end_point.first,
          lat: @end_point.last,
          image_url: helpers.asset_url('end_point.svg')
        },
      ]
    end
    # @email = @itinerary.user.email

    @iti_bus = @itinerary.itinerary_buses.first
    @bus = @iti_bus.bus

    @route_geo = build_approaching_route(@bus, @starting_point)

    @direction = @bus.star_destination
    @star_short_name = @bus.star_line_short_name
    @colour_line = Line.find_by(star_line_id: @bus[:star_line_id]).colour

    @image_thief = thief()
    @image_agent = agent()
    @image_speaker = speaker()
    @image_garbage = garbage()
    @image_people = people()
    @image_nose = nose()
    @image_url = helpers.asset_url('bus_marker3.png')

  end

  def mark_as_favorite
    @itinerary = Itinerary.find(params[:id])
    @itinerary.favorite = !@itinerary.favorite
    @itinerary.save

    respond_to do |format|
      format.html
      format.text { render partial: "itineraries/favorite", locals: { itinerary: @itinerary }, formats: [:html] }
    end
  end

  def favorites
    @itineraries_fav = Itinerary.where(favorite: true, user: :current_user).to_a
    # @itineraries = @itineraries_fav.map do |itinerary|
    #   starting_point = itinerary.route.split(";").first.split(",").map(&:to_f)
    #   end_point = itinerary.route.split(";").last.split(",").map(&:to_f)
    #   @departing = Geocoder.coordinates(starting_point).join(",")+",400"
    #   @arrival = Geocoder.coordinates(end_point).join(",")+",400"

    #   @itineraries_data = FetchItineraryService.new(@departing, @arrival).call
    #   iti = @itineraries_data.first
    #   @bus = Bus.find(itinerary.bus_ids[0])

    #   @bus.star_line_short_name = iti[:bus_name]
    #   itinerary.update(
    #     user: current_user,
    #     departing_time: iti[:departing_time],
    #     arrival_time: iti[:arrival_time]
    #   )
    #   itinerary.itinerary_buses.update(
    #   bus: @bus,
    #   itinerary: itinerary,
    #   starting_point: itinerary.starting_point,
    #   end_point: itinerary.end_point,
    #   departing_time: iti[:departing_time],
    #   arrival_time: iti[:arrival_time]
    # )

  end

  private

  def build_approaching_route(bus, starting_point)
    url = "https://data.explore.star.fr/api/records/1.0/search/?dataset=tco-bus-vehicules-position-tr&q=&sort=idbus&facet=numerobus&facet=nomcourtligne&facet=sens&facet=destination&refine.idbus=#{bus.star_bus_id}&apikey=75c8827dffd58d7e41b4b42de99ef7de9603f4f8cb28cf4bc9746306"
    bus_ser = URI.parse(url).open.read
    bus_position = JSON.parse(bus_ser)["records"].first["fields"]["coordonnees"]

    coordinates = "#{bus_position.last},#{bus_position.first};#{starting_point.first},#{starting_point.last}"

    url = "https://api.mapbox.com/optimized-trips/v1/mapbox/walking/#{coordinates}?roundtrip=false&destination=last&overview=full&steps=true&geometries=geojson&source=first&access_token=#{ENV["MAPBOX_API_KEY"]}"
    trip_ser = URI.parse(url).open.read
    trip_data = JSON.parse(trip_ser)

    return trip_data["trips"].first["geometry"]
  end
end

app/helpers/itinerary_helper.rb
module ItineraryHelper
  def arrives_after(departing_time)
    (departing_time.localtime("+01:00") - Time.now).to_i / 60
  end

  def trip_time(arrival_time)
    (arrival_time.localtime("+01:00") - Time.now).to_i / 60
  end
end

app/views/itineraries/_favorite.html.erb
<i class="fas fa-star <%= 'fa-star-active' if itinerary.favorite %>"></i>

app/views/itineraries/favorites.html.erb
<div class="d-none" id="index"></div>

<div class="itineraries--info" style='height:auto'>
  <div class="container">
    <% if @itineraries_fav.length > 0 %>
      <% @itineraries_fav.each_with_index do |itinerary, i| %>

        <div style='margin:5vh 0'>
          <%= link_to itinerary_path(itinerary) do %>
            <div class="trip-option">
              <div class="trip-title">
                <h2>Favori <%= i + 1 %></h2>

                <div class="bus-status-container">
                  <%= image_tag("smell.svg", class: "#{'active' if itinerary.itinerary_buses.first.bus.bad_smell_level}") %>
                  <%= image_tag("trash.svg",class: "#{'active' if itinerary.itinerary_buses.first.bus.cleanliness_level}") %>
                  <%= image_tag("agent.svg",class: "#{'active' if itinerary.itinerary_buses.first.bus.agent}") %>
                  <%= image_tag("noise.svg",class: "#{'active' if itinerary.itinerary_buses.first.bus.noise_level}") %>
                  <%= image_tag("unsafe.svg",class: "#{'active' if itinerary.itinerary_buses.first.bus.safetiness}") %>
                  <%= image_tag("crowded.svg", class: "#{'active' if itinerary.itinerary_buses.first.bus.crowd_level}") %>
                </div>
              </div>

              <div class="trip d-flex justify-content-between">

                <% itinerary.itinerary_buses.each do |iti_bus| %>
                  <div class="trip-logos">
                    <div class="trip-step">
                      <div class="btn-line-sm" style=" color: black; background-color:<%= itinerary.colour %>; font-size:<%= 32 / iti_bus.bus.star_line_short_name.length%>px;">
                        <span class="shortName"><%= iti_bus.bus.star_line_short_name %></span>
                      </div>
                      <div class="line"></div>
                      <%= image_tag("end_point.svg")%>
                    </div>

                    <div class="trip-step-journey-infos">
                      <div class="trip-departure">
                        <div class="arret-depart"><%= iti_bus.starting_point %></div>
                      </div>

                      <div class="trip-ending">
                        <div class="arret-end"><%= iti_bus.end_point %></div>
                      </div>
                    </div>
                  </div>
                <% end %>
              </div>
          <% end %>
        </div>
      <% end %>
    <% else %>
      <div class="trip-option">
        <h2 class="mt-3">Vous n'avez pas encore des trajets favoris! 🧐</h2>
      </div>
    <% end %>
  </div>
</div>

app/views/itineraries/index.html.erb
<style>
    body {
      position:fixed;
      height:100%;
      width:100%;
    }
</style>

<div class="d-none" id="index"></div>

<div>
  <div class="container">
    <%= form_tag itineraries_path, method: :get, html: { class: 'itineraries' }  do %>
      <%= text_field_tag :departure,
        params[:departure],
        class: "form-control w-100 address-input",
        placeholder: "Départ"
       %>
       <div class="arrival d-flex">
        <%= text_field_tag :arrival,
          params[:arrival],
          class: "form-control w-100 address-input",
          placeholder: "Arrivée"
        %>
        <div id="go" ><%= submit_tag "Go", class: "btn btn-primary" %></div>
    <% end %>
  </div>
</div>


<%# BARRES DE RECHERCHES %>
<% if params[:departure] && params[:arrival] %>
  <div class="itineraries--info">
    <div class="container">
      <div class="itineraries--summary d-flex flex-column mb-4">
        <div class="summary--departure d-inline-flex align-items-center">

          <%= image_tag("starting_point.svg", class:'starting-point-svg')%>

          <span class="sub-info-container"> <span class="sub-info">Départ </span><%= params[:departure] %></span>

        </div>


        <%= image_tag("route.svg",style: 'width: 4px; height: 21px; margin: 5px 0px 5px 7px' )%>

        <div class="summary--arrival d-inline-flex align-items-center">

           <%= image_tag("end_point.svg", class:'ending-point-svg')%>
          <span class="sub-info-container"> <span class="sub-info">Arrivée </span><%= params[:arrival] %></span>
        </div>
      </div>


      <% @itineraries.each_with_index do |itinerary, index| %>
        <div class="d-none itineraryCoordinates" data-id="<%= itinerary.id %>" data-coordinates="<%= itinerary.route %>" data-colour="<%= itinerary.colour %>"></div>
        <%= link_to itinerary_path(itinerary) do %>
          <div class="trip-option">
            <div class="trip-title">
              <h2>Itinéraire <%= index + 1 %></h2>

              <div class="bus-status-container">
                <%= image_tag("smell.svg", class: "#{'active' if itinerary.itinerary_buses.first.bus.bad_smell_level}") %>
                <%= image_tag("trash.svg",class: "#{'active' if itinerary.itinerary_buses.first.bus.cleanliness_level}") %>
                <%= image_tag("agent.svg",class: "#{'active' if itinerary.itinerary_buses.first.bus.agent}") %>
                <%= image_tag("noise.svg",class: "#{'active' if itinerary.itinerary_buses.first.bus.noise_level}") %>
                <%= image_tag("unsafe.svg",class: "#{'active' if itinerary.itinerary_buses.first.bus.safetiness}") %>
                <%= image_tag("crowded.svg", class: "#{'active' if itinerary.itinerary_buses.first.bus.crowd_level}") %>
              </div>
            </div>

            <div class="trip d-flex justify-content-between">

              <% itinerary.itinerary_buses.each_with_index do |iti_bus, index| %>
                <div class="trip-logos">
                  <div class="trip-step">
                    <div class="btn-line-sm" style=" color: black; background-color:<%= itinerary.colour %>; font-size:<%= 32 / iti_bus.bus.star_line_short_name.length%>px;">
                      <span class="shortName"><%= iti_bus.bus.star_line_short_name %></span>
                    </div>
                    <div class="line"></div>
                    <%= image_tag("end_point.svg")%>
                  </div>


                  <div class="trip-step-journey-infos">
                    <div class="trip-departure">
                      <div class="arret-depart"><%= iti_bus.starting_point %></div>
                      <div class="next-bus"><%= arrives_after(iti_bus.departing_time).abs %> min</div>
                    </div>
                    <div class="trip-ending">
                      <div class="arret-end"><%= iti_bus.end_point %></div>
                      <div class="bus-arrival-time"><%= trip_time(itinerary.arrival_time) %> min </div>
                    </div>
                  </div>

                </div>
              <% end %>
           </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
<% else %>
  <%= link_to itineraries_favorites_path do  %>
    <div class="bookmark">
      <div class="star"><i class="fas fa-star"></i></div>
    </div>
  <% end %>
  <div class="profile profile-logo">
    <%= image_tag("single-man-circle.svg", style: "scale:1.2;") %>
    <div class="menu-main">
      <%# <img src="bell.svg" alt="My Happy SVG" /> %>
      <%= image_tag("bell.svg", class: "bell") %>
      <%= link_to image_tag("signout.svg", class: "signoutsvg"), destroy_user_session_path, :method => :delete, :confirm => "Are you sure?" %>
    </div>
  </div>
<% end %>
<%# <div id="nav" class="wrapcircles closed">
  <div class="circle c-1"><span><a class="link" href="#"></a></span></div>
  <div class="circle c-2"><span><a class="link" href="#"></a></span></div>
  <div class="circle c-3"><span><a class="link" href="https://codepen.io/Chrisstar"></a></span></div>
  <div class="circle c-4"><span><a class="link" href="https://www.twitter.com/DaChrisstar"></a></span></div>
  <div id="click" class="circle c-5"><span><a class="link"></a></span></div>
</div> %>

app/views/itineraries/show.html.erb
<div class="d-none itineraryCoordinates" data-id="<%= @itinerary.id %>" data-coordinates="<%= @itinerary.route %>" data-colour="<%= @itinerary.colour %>"></div>
<div class="d-none" id="show"></div>
<div clas="d-none" id="routeGeo" data-route="<%= @route_geo.to_json %>"></div>
<div clas="d-none" id="bus-id" data-id="<%= @bus.star_bus_id %>"></div>


<div class="bus-info">
    <div class="status-container">
    <%= simple_form_for @bus do |f| %>

        <div class="status-ligne">
             <%= f.input  :cleanliness_level, label: @image_garbage.html_safe , input_html: {class: 'bus-status bus-status-invisible',checked: @bus.cleanliness_level} %>
             <%= f.input  :safetiness, label: @image_thief.html_safe , input_html: {class: 'bus-status bus-status-invisible',checked: @bus.safetiness} %>

        </div>
        <div class="status-ligne">
             <%= f.input  :noise_level, label: @image_speaker.html_safe, input_html: {class: 'bus-status bus-status-invisible',checked: @bus.noise_level} %>
             <%= f.input  :bad_smell_level, label: @image_nose.html_safe, input_html: {class: 'bus-status bus-status-invisible', checked: @bus.bad_smell_level} %>
        </div>
        <div class="status-ligne">
             <%= f.input  :crowd_level, label: @image_people.html_safe, input_html: {class: 'bus-status bus-status-invisible',checked: @bus.crowd_level} %>
             <%= f.input  :agent, label: @image_agent.html_safe, input_html: {class: 'bus-status bus-status-invisible',checked: @bus.agent} %>
    <% end %>
        </div>
    </div>
</div>


<div id="info-btn" style="bottom: 21.265vh;" class="profile d-none">
  <div class="info" id="i"> <%= image_tag("info-button.svg") %> </div>
  <div class="info" id="x"><i class="fas fa-times"></i></div>
</div>


<div>
  <%= link_to itineraries_path do %>
   <div class="home-btn"> <%= image_tag("home.svg",class: "home-logo")%> </div>
  <% end %>

  <div class="intinerary-infos">
    <div class="line-logo-big">

      <div class="btn-line-big" style="background-color:<%= @colour_line %>; font-size:<%= 64 / @star_short_name.length%>px;"> <%= @star_short_name %></div>

    </div>

    <div class="direction-terminus">
      <span class="direction">
      Direction
      </span>

      <%= @direction%>
      <div id="star" data-id="<%= @itinerary.id %>">
        <%= render "itineraries/favorite", itinerary: @itinerary %>
      <%# <%= f.input  :favorit=begin  =ende, label: '<i class="fas fa-star"></i>'.html_safe, input_html: {class: 'favorite'} %>
      </div>
    
    </div>

  <div class="container">
      <%# Bloc à loop %>
      <div class="bus-infos" style="margin-top:0;">
        <div class="d-flex justify-content-between">
          <div class="left-info">

           <div id="time-bus">Bus dans <span class="bus-arrival"><%= arrives_after(@itinerary.departing_time) %></span> min. <br><%= image_tag("bus.svg")%></div>
           <div id="time-arrive" class="d-none">Arrivée : <span class="bus-arrival"><%= trip_time(@itinerary.arrival_time) %></span> min.</div>
          </div>

          <div class="right-info" id="bus-status-container">
            <%= render "buses/status", bus: @bus, image_garbage: @image_garbage, image_thief: @image_thief, image_speaker: @image_speaker, image_nose: @image_nose, image_people: @image_people, image_agent: @image_agent %>
          </div>
        </div>

     <%#= link_to trip_path(@itinerary) do %>
      <a href="#" id="startTrip">
        <div class="mt-3 btn btn-primary btn-block btn-fade">Je suis dans le bus</div>
      </a>
      <%= link_to trips_arrived_path, id: "endTrip", class: "d-none" do %>
        <div class="mt-3 btn btn-primary btn-block btn-fade">Je suis arrivé</div>
      <% end %>
      <%# end %>
    </div>